apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: cloudcart
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: harveen421/cloudcart-user-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cloudcart-secrets
              key: USER_DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cloudcart-secrets
              key: SECRET_KEY
        - name: ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: cloudcart-config
              key: ALGORITHM
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: cloudcart-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: cloudcart
spec:
  selector:
    app: user-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
