apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: cloudcart
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: cloud-native-microservices-app-product-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cloudcart-secrets
              key: PRODUCT_DATABASE_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cloudcart-config
              key: INVENTORY_SERVICE_URL
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8002
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
