apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudcart-config
  namespace: cloudcart
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  USER_SERVICE_URL: "http://user-service:8001"
  PRODUCT_SERVICE_URL: "http://product-service:8002"
  ORDER_SERVICE_URL: "http://order-service:8003"
  INVENTORY_SERVICE_URL: "http://inventory-service:8004"
  NEXT_PUBLIC_API_GATEWAY_URL: "http://localhost:8000"