apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: cloudcart
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: cloud-native-microservices-app-inventory-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8004
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cloudcart-secrets
              key: INVENTORY_DATABASE_URL
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8004
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 10
