apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cloudcart
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: cloud-native-microservices-app-api-gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cloudcart-config
              key: USER_SERVICE_URL
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cloudcart-config
              key: PRODUCT_SERVICE_URL
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cloudcart-config
              key: ORDER_SERVICE_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cloudcart-config
              key: INVENTORY_SERVICE_URL
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
